### ISSUE TITLE
Requirements should only be used to eligibility criteria

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/ocds_requirements_extension#4]
From work in Kiev:

(1) Requirements should only be for ``eligibilityCriteria`` which are pass/fail criteria applying to a bidder, **not** ``awardCriteria`` which can be evaluative criteria (pass/fail OR weighted) that apply to the item or the bidder. At the moment we suggest it can be used for both, and give an example based on properties of the item.

(2) Requirements may (in some cases) vary by ``lot`` - suggested a ```relatedLot``` property may be required in some cases. 

We identified a couple of terminological issues to clarify:

* Qualification criteria - pass/fail  - is the bidder eligible 'in general' to participate in procurement
* Eligibility criteria - pass/fail - is the bid eligible
* Selection criteria - weighted scoring - how should features of the bid or bidder be factored into the selection (against pricing criterial also)

We need to:

* [ ] (1) Evaluate where use of requirements is currently recommended;
* [ ] (2) Review whether we can use the requirements data model for award criteria, or whether the [ProZorro features approach](https://github.com/open-contracting/standard/issues/499) is appropriate for this
* [ ] (3) If (2) then check whether we should use the same object, but different properties for (e.g.) ``eligibilityCriteriaStructured`` and ``awardCriteriaStructured``

Note that EU might just need very simple awardCriteria breakdown to who balance between price and non-price criteria. 

Related issues:

* https://github.com/open-contracting/standard/issues/385#issuecomment-278358093
* https://github.com/open-contracting/standard/issues/499

**Comment by andrewlorien** [comment]
In NSW eTendering and AusTender (Australian commonwealth) there are criteria based on the CCCEV. They are never evaluated automatically, and many of the responses are documents (insurances, evidence of previous performance, qualifications etc).  Each criteria is given a pass/fail rating during the evaluation phase. These are prequalifications, so a contract is not directly awarded based on the status of the criteria.
Based on Tim's comment, we would have an Eligibility Criteria for each item, and (I assume) when every item passes the tenderer becomes qualified.  From the information on this ticket at the moment, I can't decide where the pass/fail for each individual item would go.  Working on that this week.

**Comment by jpmckinney** [comment]
Moved https://github.com/open-contracting/ocds-extensions/issues/4
